//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_STOCK_TRANSFER
    {
        public long STOCK_TRANSFER_ID { get; set; }
        public string STOCK_TRANSFER_NUMBER { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<bool> IS_SEND { get; set; }
        public long ITEM_ID { get; set; }
        public int TRANS_QUANTITY { get; set; }
        public string SEARCH_CODE { get; set; }
        public string ITEM_NAME { get; set; }
        public string BARCODE { get; set; }
        public Nullable<int> TOTAL_STOCK_QNT { get; set; }
        public Nullable<long> COMPANY_ID { get; set; }
        public string FROM_GODOWN { get; set; }
        public string TO_GODOW { get; set; }
        public string RECEIVED_BY { get; set; }
        public string BUSINESS_LOCATION { get; set; }
        public Nullable<long> FROM_GODOWN_ID { get; set; }
        public Nullable<long> TO_GODOWN_ID { get; set; }
        public Nullable<long> RECEIVED_BY_ID { get; set; }
        public Nullable<long> BUSINESS_LOCATION_ID { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
        public Nullable<bool> IS_NEGATIVE_STOCK_MESSAGE { get; set; }
        public Nullable<long> USER_ID { get; set; }
    }
}
