//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_TAX
    {
        public int TAX_ID { get; set; }
        public string TAX_NAME { get; set; }
        public Nullable<decimal> TAX_VALUE { get; set; }
        public Nullable<long> COMPANY_ID { get; set; }
        public Nullable<bool> IS_SEPARATE { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
        public Nullable<long> USER_ID { get; set; }
        public string COMPANY { get; set; }
    }
}
