//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_FINANCIAL
    {
        public long FINANCIAL_ID { get; set; }
        public Nullable<long> INVOICE_ID { get; set; }
        public Nullable<decimal> FINANCIAL_AMOUNT { get; set; }
        public Nullable<long> FINANCIAL_CREDIT_AC { get; set; }
        public Nullable<long> FINANCIAL_CREDIT_ID { get; set; }
        public Nullable<long> USER_ID { get; set; }
    }
}
