//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ORDER
    {
        public long ORDER_ID { get; set; }
        public Nullable<long> ITEM_ID { get; set; }
        public Nullable<int> ORDER_QUANTITY { get; set; }
        public Nullable<double> DISCOUNT { get; set; }
        public Nullable<double> ODER_COST { get; set; }
        public Nullable<bool> IS_DISCOUNT_IN_PERCENTAGE { get; set; }
        public Nullable<long> COMPANY_ID { get; set; }
        public Nullable<long> USER_ID { get; set; }
    }
}
