//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CUSTOMER_GROUP
    {
        public long CUSTOMER_GROUP_ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<long> COMPANY_ID { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
        public Nullable<long> USER_ID { get; set; }
    }
}
