//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ESTIMATE1
    {
        public int ID { get; set; }
        public string ESTIMATE_NO { get; set; }
        public Nullable<int> ITEM_ID { get; set; }
        public string ITEM_NAME { get; set; }
        public string BARCODE { get; set; }
        public Nullable<int> CURRENT_QTY { get; set; }
        public string MEASURING_UNIT { get; set; }
        public string TAX_NAME { get; set; }
        public Nullable<decimal> TAX_PRICE { get; set; }
        public Nullable<decimal> DISCOUNT { get; set; }
        public Nullable<decimal> TOTAL_WITH_TAX { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<System.DateTime> ESTIMATE_DATE { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
    }
}
