//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_RECEIVE_ITEM
    {
        public int NEWRECEIVE_ID { get; set; }
        public Nullable<long> COMPANY_ID { get; set; }
        public Nullable<long> SELECT_BUSINESS_LOCATION_ID { get; set; }
        public string BARCODE { get; set; }
        public string ITEM_NAME { get; set; }
        public string SEARCH_CODE { get; set; }
        public string SUPPLIER_INVOICE_NO { get; set; }
        public Nullable<System.DateTime> RECEIVE_DATE { get; set; }
        public Nullable<System.DateTime> RECEIVED_ITEM_ON_DATE { get; set; }
        public Nullable<long> PO_NUMBER_ID { get; set; }
        public Nullable<long> SUPPLIER_ID { get; set; }
        public Nullable<int> PAYMENT_TERMS { get; set; }
        public Nullable<long> GODOWN_ID { get; set; }
        public string RECEIVING_EMPLOYEE { get; set; }
        public Nullable<decimal> DISCOUNT_FLAT { get; set; }
        public Nullable<decimal> DISCOUNT_PERCENT { get; set; }
        public Nullable<decimal> ADDTIONAL_CHARGES { get; set; }
        public Nullable<decimal> SUB_TOTAL_BEFORETAX { get; set; }
        public Nullable<decimal> TOTAL_TAX_AMT { get; set; }
        public Nullable<decimal> SUB_TOTAL { get; set; }
        public Nullable<decimal> ROUND_OFF_ADJUSTMENTAMT { get; set; }
        public Nullable<decimal> TOTAL_AMT { get; set; }
        public Nullable<decimal> USE_SUPPLIER_ADVANCE_AMT { get; set; }
        public Nullable<decimal> GRAND_TOTAL { get; set; }
        public string NOTE { get; set; }
        public Nullable<bool> IS_REC_WITH_PO { get; set; }
        public string FILTER_HIERARCHY { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
        public string PO_NUMBER { get; set; }
        public string SUPPLIER { get; set; }
        public string BUSINESS_LOCATION { get; set; }
        public string GODOWN { get; set; }
        public Nullable<bool> DISCOUNT_BEFOR_TAX { get; set; }
        public Nullable<bool> AUTO_SAVE_IN_DRAFT { get; set; }
        public Nullable<bool> FOCUS_LAST_ADD_ITEM { get; set; }
        public Nullable<bool> ITEM_ENTRY_TEMPLATE { get; set; }
        public Nullable<bool> PAY_IN_CASH { get; set; }
        public Nullable<bool> APPLY_FPR_EFFECTVE_PRICE { get; set; }
        public Nullable<decimal> INVOICE_DIS_AMT { get; set; }
        public string RECEIVED_ITEM_ENTRY_NO { get; set; }
        public Nullable<long> USER_ID { get; set; }
        public Nullable<System.DateTime> SUPPLIER_INVOICE_DATE { get; set; }
        public Nullable<int> Item_Id { get; set; }
    }
}
