//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_REPORT
    {
        public long REPORT_ID { get; set; }
        public string REPORT_SL_NO { get; set; }
        public string REPORT_NAME { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
        public string CREATED_BY { get; set; }
    }
}
