//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_COMPANY
    {
        public int COMAPNY_ID { get; set; }
        public string COMPANY_NAME { get; set; }
        public string SHOPNAME { get; set; }
        public string PREFIX { get; set; }
        public string PREFIX_NUM { get; set; }
        public string TIN_NUMBER { get; set; }
        public string ADDRESS_1 { get; set; }
        public string ADDRESS_2 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string COUNTRY { get; set; }
        public string PHONE_NUMBER { get; set; }
        public string MOBILE_NUMBER { get; set; }
        public string EMAIL { get; set; }
        public string WEBSITE { get; set; }
        public Nullable<bool> IS_WARNED_FOR_NEGATIVE_STOCK { get; set; }
        public Nullable<bool> IS_WARNED_FOR_LESS_SALES_PRICE { get; set; }
        public string TAX_PRINTED_DESCRIPTION { get; set; }
        public Nullable<short> FIRST_DAY_OF_FINANCIAL_YEAR { get; set; }
        public Nullable<short> FIRST_MONTH_OF_FINANCIAL_YEAR { get; set; }
        public Nullable<long> BANK_ID { get; set; }
        public Nullable<decimal> DEFAULT_TAX_RATE { get; set; }
        public string PIN { get; set; }
        public string IMAGE_PATH { get; set; }
    }
}
