//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_INVOICE
    {
        public long INVOICE_ID { get; set; }
        public string INVOICE_NUMBER { get; set; }
        public Nullable<int> INVOICE_STATUS_ID { get; set; }
        public Nullable<System.DateTime> INVOICE_DATE { get; set; }
        public Nullable<System.DateTime> INVOICE_DUE_DATE { get; set; }
        public Nullable<long> INVOICE_CUSTOMER_ID { get; set; }
        public Nullable<long> INVOICE_COURIER_ID { get; set; }
        public string INVOICE_COURIER_NAME { get; set; }
        public Nullable<long> INVOICE_PAYMENT_ID { get; set; }
        public Nullable<int> INVOICE_PO_NUMBER { get; set; }
        public Nullable<double> INVOICE_TAX { get; set; }
        public Nullable<double> INVOICE_TAX2 { get; set; }
        public Nullable<System.DateTime> IS_PRINT_DUE_DATE { get; set; }
        public Nullable<int> FREQUENCY_TYPE_ID { get; set; }
        public Nullable<bool> IS_RECCURANCE_INVOICE { get; set; }
        public Nullable<int> INTERVAL { get; set; }
        public Nullable<System.DateTime> NEXT_INVOICE_DATE { get; set; }
        public Nullable<System.DateTime> FINAL_INVOICE_DATE { get; set; }
        public Nullable<bool> IS_RECUR_UNTIL_VOIDED { get; set; }
        public Nullable<int> GENERATE_NEW_INVOICE { get; set; }
        public Nullable<bool> IS_QUOTE { get; set; }
        public Nullable<System.DateTime> VALID_UNTIL { get; set; }
        public Nullable<long> COMPANY_ID { get; set; }
        public Nullable<long> USER_ID { get; set; }
    }
}
