//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_BANK
    {
        public long BANK_ID { get; set; }
        public Nullable<long> COMPANY_ID { get; set; }
        public string BANK_NAME { get; set; }
        public string IFSC_CODE { get; set; }
        public Nullable<bool> IS_DELETED { get; set; }
        public string ADDRESS_1 { get; set; }
        public string ADDRESS_2 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string PIN_CODE { get; set; }
        public string PHONE_NUMBER { get; set; }
        public string MOBILE_NUMBER { get; set; }
        public string FAX_NUMBER { get; set; }
        public string EMAIL { get; set; }
        public string WEBSITE { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public string BANK_CODE { get; set; }
        public string COUNTRY { get; set; }
    }
}
