//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CHEQUE
    {
        public long CHEQUE_ID { get; set; }
        public Nullable<long> INVOICE_ID { get; set; }
        public Nullable<decimal> CHEQUE_AMOUNT { get; set; }
        public string CHEQUE_NO { get; set; }
        public string CHEQUE_BRANCH { get; set; }
        public Nullable<System.DateTime> CHEQUE_DATE { get; set; }
        public Nullable<long> CHEQUE_BANK_AC { get; set; }
        public Nullable<long> CHAEQE_BANK_AC_ID { get; set; }
        public Nullable<long> USER_ID { get; set; }
    }
}
