//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_AUTO_GENERATE_CODE_FOR_PRODUCT
    {
        public long ID { get; set; }
        public string AUTO_GENERATE_CODE_FOR_PRODUCT { get; set; }
        public string DEFINE_CODE { get; set; }
        public Nullable<long> COMPANY_ID { get; set; }
        public Nullable<long> USER_ID { get; set; }
    }
}
