//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CATAGORY
    {
        public long CATAGORY_ID { get; set; }
        public string CATAGORY_NAME { get; set; }
        public string BAR_CODE_PREFIX { get; set; }
        public string CATAGORY_DEC { get; set; }
        public string DISPLAY_INDEX { get; set; }
        public Nullable<bool> IS_NOT_PROTAL { get; set; }
        public Nullable<long> COMPANY_ID { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
        public Nullable<long> USER_ID { get; set; }
    }
}
