//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_supppaydetails
    {
        public long Id { get; set; }
        public Nullable<long> Supp_ID { get; set; }
        public Nullable<System.DateTime> payduedate { get; set; }
        public Nullable<long> noofday { get; set; }
        public Nullable<decimal> totalamount { get; set; }
        public Nullable<decimal> pendingamoun { get; set; }
        public Nullable<decimal> adjustedamount { get; set; }
        public Nullable<System.DateTime> suppinvdate { get; set; }
        public string recitementryno { get; set; }
        public string goodsecno { get; set; }
        public string suppinv { get; set; }
        public Nullable<decimal> totaltax { get; set; }
        public Nullable<System.DateTime> DOU { get; set; }
        public Nullable<bool> Delete { get; set; }
    }
}
