//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_VENDORS
    {
        public int VENDOR_ID { get; set; }
        public Nullable<long> COMPANY_ID { get; set; }
        public string CONTACT_NAME { get; set; }
        public string ADDRESS_1 { get; set; }
        public string ADDRESS_2 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string POSTAL { get; set; }
        public string PHONE_NUMBER { get; set; }
        public string EAX_NUMBER { get; set; }
        public string EMAIL_ADDRESS { get; set; }
        public string WEB_SITE { get; set; }
        public Nullable<double> CREDIT_LIMIT { get; set; }
        public string SUPPLIER_CODE { get; set; }
        public string VAT_NUMBER { get; set; }
        public string CST_NUMBER { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
        public Nullable<bool> IS_PREFERRED { get; set; }
        public Nullable<int> PAYMENT_DAYS { get; set; }
        public string LAST_NAME { get; set; }
        public string TELEPHONE_NUMBER { get; set; }
        public string IMAGE_PATH { get; set; }
    }
}
