//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_BANK_ACCOUNT
    {
        public long BANK_ACCOUNT_ID { get; set; }
        public Nullable<long> BANK_ID { get; set; }
        public Nullable<long> COMPANY_ID { get; set; }
        public string BRANCH_NAME { get; set; }
        public string ACCOUNT_DESCRIPTION { get; set; }
        public string ACCOUNT_SEARCH_CODE { get; set; }
        public string ACCOUNT_NUMBER { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
        public string PRINTING_FORMAT { get; set; }
        public Nullable<long> USER_ID { get; set; }
    }
}
