//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CUSTOMER
    {
        public int CUSTOMER_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string CUSTOMER_NUMBER { get; set; }
        public int CATEGORY_ID { get; set; }
        public Nullable<bool> SAMEBILLINGANDSHIPPING_ADDRESS { get; set; }
        public string NOTES { get; set; }
        public string VAT_NUMBER { get; set; }
        public string CST_NUMBER { get; set; }
        public bool IS_ACTIVE { get; set; }
        public Nullable<bool> DEFAULT_CREIT_LIMIT { get; set; }
        public string CUSTOMER_GROUP { get; set; }
        public string LOYALTY_NO { get; set; }
        public string REFERRED_BY { get; set; }
        public string SEARCH_CODE { get; set; }
        public Nullable<long> COMPANY_ID { get; set; }
        public Nullable<bool> IS_ENROLLED_FOR_LOYALITY { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
        public Nullable<decimal> OPENING_BALANCE { get; set; }
        public string TIN_NUMBER { get; set; }
        public string PAN_NUMBER { get; set; }
        public string BUSINESS_LOCATION { get; set; }
        public Nullable<long> BUSINESS_LOCATION_ID { get; set; }
        public string IMAGE_PATH { get; set; }
        public Nullable<long> USER_ID { get; set; }
    }
}
