//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_RECEIVE_PAYMENT
    {
        public long RECEIVE_PAYMENT_ID { get; set; }
        public string RECEIVE_PAY_NO { get; set; }
        public Nullable<long> BUSINESS_LOCATION_ID { get; set; }
        public string BUSINESS_LOCATION { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<long> CUSTOMER_ID { get; set; }
        public string CUSTOMER { get; set; }
        public string CUSTOMER_EMAIL { get; set; }
        public Nullable<bool> IS_EMAIL_SEND { get; set; }
        public string CUSTOMER_CONTACT_NO { get; set; }
        public Nullable<decimal> OTHER_PAY_AMT { get; set; }
        public Nullable<decimal> CURRENT_PAY_AMT { get; set; }
        public Nullable<decimal> TOTAL_SELECTED_PAY_AMT { get; set; }
        public Nullable<decimal> PENDING_AMT { get; set; }
        public Nullable<decimal> TOTAL_REC_AMT { get; set; }
        public Nullable<decimal> RETURNABLE_AMT { get; set; }
        public Nullable<long> COMPANY_ID { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
        public Nullable<long> USER_ID { get; set; }
        public Nullable<long> CASH_REGISTERID { get; set; }
    }
}
