//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_LOYALTY
    {
        public long LOYALTY_ID { get; set; }
        public string SETTINGSNAME { get; set; }
        public string WEIGHTAGE { get; set; }
        public Nullable<System.DateTime> FROMDATE { get; set; }
        public Nullable<System.DateTime> TODATE { get; set; }
        public string CUSTOMERGROUP { get; set; }
        public string COLLECTION { get; set; }
        public Nullable<bool> ISACTIVE { get; set; }
        public Nullable<bool> ISDEFAULT { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
        public Nullable<long> COMPANY_ID { get; set; }
        public Nullable<long> USER_ID { get; set; }
        public Nullable<decimal> InvoiceExceeding { get; set; }
        public Nullable<decimal> FlatPoints { get; set; }
    }
}
