//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PO_PAYMENT
    {
        public long PO_ID { get; set; }
        public string PO_NUMBER { get; set; }
        public Nullable<System.DateTime> DELIVERY_DATE { get; set; }
        public Nullable<bool> IS_SEND_MAIL { get; set; }
        public Nullable<long> COMPANY_ID { get; set; }
        public string BUSINESS_LOCATION_ID { get; set; }
        public string DELIVER_ID { get; set; }
        public string BUSINESS_LOCATION { get; set; }
        public string DELIVER_TO { get; set; }
        public string SUPPLIER_ID { get; set; }
        public string SUPPLIER_NAME { get; set; }
        public string SUPPLIER_MAIL { get; set; }
        public string TERMS { get; set; }
        public Nullable<decimal> TOTAL_TAX { get; set; }
        public Nullable<decimal> TOTAL_AMOUNT { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
        public Nullable<System.DateTime> PO_DATE { get; set; }
        public Nullable<long> USER_ID { get; set; }
        public string PO_STATUS { get; set; }
        public string PO_TYPE { get; set; }
    }
}
