//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CASH_REG
    {
        public long CASH_REG_ID { get; set; }
        public string CASH_REG { get; set; }
        public Nullable<decimal> CASH_AMOUNT { get; set; }
        public Nullable<long> INVOICE_ID { get; set; }
        public Nullable<System.DateTime> CASH_REG_DATE { get; set; }
        public Nullable<long> USER_ID { get; set; }
    }
}
