//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PO_ITEMS
    {
        public int PO_ID { get; set; }
        public Nullable<int> PO_ITEM_ID { get; set; }
        public Nullable<long> PO_NUMBER { get; set; }
        public Nullable<decimal> PO_DISCOUNT { get; set; }
        public Nullable<decimal> PO_TOTAL_AMOUNT { get; set; }
        public Nullable<int> PO_QTY { get; set; }
        public Nullable<decimal> PO_TAX { get; set; }
    }
}
