//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_OPENING_STOCK
    {
        public long OPENING_STOCK_ID { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<long> ITEM_ID { get; set; }
        public Nullable<long> BUSINESS_LOC_ID { get; set; }
        public Nullable<long> COMPANY_ID { get; set; }
        public Nullable<decimal> OPRNING_BAL { get; set; }
        public Nullable<decimal> CLOSING_BAL { get; set; }
        public string BARCODE { get; set; }
        public string ITEM_NAME { get; set; }
        public string GODOWN { get; set; }
        public string COMPANY_NAME { get; set; }
        public Nullable<int> OPN_QNT { get; set; }
        public string BUSSINESS_LOCATION { get; set; }
    }
}
