//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USER
    {
        public long USER_ID { get; set; }
        public string PASSWORD { get; set; }
        public long COMPANY_ID { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public byte[] LOGIN_TIME { get; set; }
        public string MAC_ADDRESS { get; set; }
        public string ROLE { get; set; }
    }
}
