//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SUPPLIER
    {
        public long SUPPLIER_ID { get; set; }
        public string SUPPLIER_CODE { get; set; }
        public string SUPPLIER_NAME { get; set; }
        public string SEARCH_CODE { get; set; }
        public string VAT_NO { get; set; }
        public string CST_NO { get; set; }
        public string TIN_NO { get; set; }
        public string PAN_NO { get; set; }
        public string ADDRESS_1 { get; set; }
        public string ADDRESS_2 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIP_CODE { get; set; }
        public Nullable<decimal> OPENING_BALANCE { get; set; }
        public Nullable<bool> IS_PREFERRED_SUPPLIER { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
        public Nullable<int> PAYMENT_SETTLED { get; set; }
        public string IMAGE_PATH { get; set; }
        public string CONTACT_FRIST_NAME { get; set; }
        public string CONTACT_LAST_NAME { get; set; }
        public string CONTACT_TELEPHONE_NO { get; set; }
        public string CONTACT_FAX_NO { get; set; }
        public string CONTACT_MOBILE_NO { get; set; }
        public string CONTACT_WEBSITE { get; set; }
        public string CONTACT_EMAIL { get; set; }
        public Nullable<long> COMPANY_ID { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
        public Nullable<long> USER_ID { get; set; }
    }
}
