//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_REPORT_ADD
    {
        public long REPORT_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<long> REPORT_GROUP_ID { get; set; }
        public string SEARCH_CODE { get; set; }
        public string REPORT_NAME { get; set; }
        public Nullable<long> USER_ID { get; set; }
    }
}
