//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SALES_RETURN
    {
        public long SALES_RETURN_ID { get; set; }
        public string BUSINESS_LOCATION { get; set; }
        public string SALES_RETURN_NO { get; set; }
        public string BARCODE { get; set; }
        public string ITEM_NAME { get; set; }
        public Nullable<bool> IS_WITHOUT_INVOICE { get; set; }
        public Nullable<System.DateTime> RETURN_DATE { get; set; }
        public string GODOWN { get; set; }
        public Nullable<long> CUSTOMER_ID { get; set; }
        public Nullable<decimal> OUTSTANDING_BALANCE { get; set; }
        public string INVOICE_NO { get; set; }
        public string REFERENCE_NUMBER { get; set; }
        public Nullable<decimal> TAX_AMOUNT { get; set; }
        public Nullable<decimal> FREIGHT_CHARGE { get; set; }
        public Nullable<decimal> PACKING_CHARGE { get; set; }
        public Nullable<decimal> TOTAL_AMOUNT { get; set; }
        public Nullable<int> ROUND_OFF_AMOUNT { get; set; }
        public Nullable<decimal> GRAND_TOTAL { get; set; }
        public Nullable<decimal> SUBSIDY_AMOUN { get; set; }
        public Nullable<decimal> CUS_PENDING_AMOUNT { get; set; }
        public string NOTES { get; set; }
        public Nullable<long> COMPANY_ID { get; set; }
        public string SEARCH_CODE { get; set; }
        public string SALES_EXECUTIVE { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
        public Nullable<long> USER_ID { get; set; }
    }
}
