//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_UNIT_MEASURING
    {
        public long UNIT_ID { get; set; }
        public string MEASURING_NAME { get; set; }
        public string SHORT_INDAX { get; set; }
        public string IMAGE_PATH { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
        public Nullable<long> COMPANY_ID { get; set; }
        public Nullable<long> USER_ID { get; set; }
    }
}
