//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ITEM_LOCATION
    {
        public long LOCATION_ID { get; set; }
        public Nullable<long> COMPANY_ID { get; set; }
        public Nullable<long> GOWDOWN_ID { get; set; }
        public string ITEM_LOCATION_NAME { get; set; }
        public string SORT_INDEX { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
        public Nullable<long> USER_ID { get; set; }
    }
}
