//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_RECEIVE_ITEM_ITEMS
    {
        public int RCV_ID { get; set; }
        public Nullable<int> RCV_ITEM_ID { get; set; }
        public Nullable<decimal> RCV_AMOUNT { get; set; }
        public Nullable<int> RCV_QTY { get; set; }
        public Nullable<decimal> RCV_TAX { get; set; }
        public Nullable<long> RCV_ITEM_ENTRY_ID { get; set; }
        public Nullable<decimal> RCV_DISCOUNT { get; set; }
    }
}
