//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_LOYALTY_Exceedings
    {
        public long ID { get; set; }
        public Nullable<long> LOYALTY_ID { get; set; }
        public Nullable<decimal> InvoiveExceeding { get; set; }
        public Nullable<decimal> Flatpoints { get; set; }
        public Nullable<long> Company_ID { get; set; }
    }
}
