//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SALE_ITEM
    {
        public int SALE_ID { get; set; }
        public Nullable<int> SALE_ITEM_ID { get; set; }
        public Nullable<int> INVOICE_ID { get; set; }
        public Nullable<decimal> ITEM_DISCOUNT { get; set; }
        public Nullable<decimal> ITEM_TOTAL_AMOUNT { get; set; }
        public Nullable<int> SALE_QTY { get; set; }
        public Nullable<decimal> ITEM_TAX { get; set; }
        public Nullable<bool> STATUS { get; set; }
    }
}
