//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmp_invoice
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string Items { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<decimal> Total_Amt { get; set; }
        public string Tax_Desc { get; set; }
        public Nullable<decimal> Taxable_Amt { get; set; }
        public Nullable<decimal> Vat_Tax { get; set; }
        public string Priceinwords { get; set; }
        public string Inv_No { get; set; }
    }
}
