//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_GROUP_SUBGROUP
    {
        public Nullable<long> REPORT_GRP_ID { get; set; }
        public string GroupName { get; set; }
        public long ParentId { get; set; }
        public Nullable<long> REPORT_ID { get; set; }
        public Nullable<long> Child { get; set; }
    }
}
