//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ITEM_ATTRIBUTE
    {
        public Nullable<int> ITEM_ID { get; set; }
        public string ITEM_NAME { get; set; }
        public string ITEM_DESCRIPTION { get; set; }
        public Nullable<double> ITEM_PRICE { get; set; }
        public Nullable<int> ITEM_PRODUCT_ID { get; set; }
        public Nullable<int> ITEM_INVOICE_ID { get; set; }
        public string KEYWORD { get; set; }
        public string ACCESSORIES_KEYWORD { get; set; }
        public string BARCODE { get; set; }
        public Nullable<int> GODOWN_ID { get; set; }
        public Nullable<long> CATAGORY_ID { get; set; }
        public string SERCH_CODE { get; set; }
        public Nullable<decimal> TAX_PAID { get; set; }
        public Nullable<decimal> TAX_COLLECTED { get; set; }
        public string PURCHASE_UNIT { get; set; }
        public string SALES_UNIT { get; set; }
        public Nullable<decimal> PURCHASE_UNIT_PRICE { get; set; }
        public Nullable<decimal> SALES_PRICE { get; set; }
        public Nullable<decimal> MRP { get; set; }
        public Nullable<int> COMPANY_ID { get; set; }
        public Nullable<int> OPN_QNT { get; set; }
        public string CATEGORY_NAME { get; set; }
        public string DISPLAY_INDEX { get; set; }
        public string ITEM_UNIQUE_NAME { get; set; }
        public string ITEM_GROUP_NAME { get; set; }
        public string REGIONAL_LANGUAGE { get; set; }
        public Nullable<decimal> SALES_PRICE_BEFOR_TAX { get; set; }
        public Nullable<System.DateTime> MODIFICATION_DATE { get; set; }
        public string CATAGORY { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
        public string ITEM_LOCATION { get; set; }
        public Nullable<decimal> WEIGHT_OF_PAPER { get; set; }
        public Nullable<decimal> WEIGHT_OF_PLASTIC { get; set; }
        public Nullable<decimal> WEIGHT_OF_FOAM { get; set; }
        public Nullable<decimal> WEIGHT_OF_CARDBOARD { get; set; }
        public string IMAGE_PATH { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string GODOWN { get; set; }
        public string COMPANY_NAME { get; set; }
        public string BUSSINESS_LOCATION { get; set; }
        public long OPENING_STOCK_ID { get; set; }
        public string TAX_PAID_NAME { get; set; }
        public string TAX_COLLECTED_NAME { get; set; }
        public Nullable<int> TAX_COLLECTED_ID { get; set; }
        public Nullable<int> TAX_PAID_ID { get; set; }
        public Nullable<int> BUSS_LOC_ID { get; set; }
        public Nullable<int> Expr1 { get; set; }
        public Nullable<int> PURCHAGE_UNIT_ID { get; set; }
        public Nullable<int> SALE_UNIT_ID { get; set; }
        public Nullable<bool> IS_ACIVE { get; set; }
        public Nullable<bool> INCLUDE_TAX { get; set; }
        public string TAX_NAME { get; set; }
        public Nullable<decimal> TAX_VALUE { get; set; }
        public string ITEM_LOCATION_NAME { get; set; }
    }
}
