//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_EMP_ACCESS_MODULE
    {
        public string MODULE_NAME { get; set; }
        public int MODULE_ID { get; set; }
        public Nullable<bool> ACTION_CREATE { get; set; }
        public Nullable<bool> EDIT { get; set; }
        public Nullable<bool> ACTION_DELETE { get; set; }
        public Nullable<bool> ACTION_VIEW { get; set; }
        public Nullable<bool> VERIFICATION { get; set; }
        public Nullable<bool> NOTIFICATION { get; set; }
        public Nullable<bool> MESSAGE { get; set; }
        public Nullable<bool> APPROVE { get; set; }
        public Nullable<long> ROLE_ID { get; set; }
        public Nullable<bool> MAILBACK { get; set; }
        public Nullable<long> ID { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<long> User_Id { get; set; }
        public Nullable<long> Company_Id { get; set; }
        public Nullable<bool> IMORT_TO_EXCEL { get; set; }
        public Nullable<bool> EXPT_TO_EXCEL { get; set; }
    }
}
